### ISSUE TITLE
Weird behavior when combined with image-zoom

### ISSUE THREAD

**Issue by danceshorribly** [CodyHouse/cd-reveal-effects-changelog#1]
If reveal-effects are combined with image-zoom the zoom only appears in the container.

For example:
A two column layout with each containing one figure elements containing one image each and image-zoom class applied to the img-element.

As you can see in the screenshot it also effects the text in the container.

![ezgif com-resize](https://user-images.githubusercontent.com/63228109/78535507-9096a380-77ec-11ea-8493-cd9c50ff03ee.gif)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up!
We just pushed a fix to the image-zoom component that solves this issue. You can get the new JS code from the component page:
https://codyhouse.co/ds/components/app/image-zoom

Let me know if you are still having issue. Cheers!
