### ISSUE TITLE
Global  `data-reveal-fx-delta` Variable

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-reveal-effects-changelog#2]
### Feature Enhancement Request 
The default of 200px doesn't work for our purposes and it's tedious to add a custom  `data-reveal-fx-delta=""` attribute to every element. Is it possible to add a global variable where this can be changed on all elements?

**Comment by sebastiano-guerriero** [comment]
Hi Emily, you can edit the `var fxRevealDelta = 200;` in the JS file of the component to set a new default value.
