### ISSUE TITLE
fxRemoveClasses gives "split method doesn't exist" error on SVG elements

### ISSUE THREAD

**Issue by alexandrebuffet** [CodyHouse/cd-reveal-effects-changelog#3]
Hi, 

I used reveal effects component on SVG elements and it works pretty well until I try it on IE11 where Reduced Motion on or Intersection Observer not supported...  Fallback method **fxRemoveClasses** gives "split method doesn't exist" error occur when trying to remove all classes starting with 'reveal-fx--'.

For now I fix it by introducing some `if (el.className instanceof SVGAnimatedString)` test. But is there a way to manage SVG elements className issues (should be className.baseVal) in this component and globaly in utility methods dealing classes?

**Comment by claudia-romano** [comment]
Hi Alexandre, 
this is a good point. A solution could be to replace `className` with `getAttribute/setAttribute` class. For example:
```
// not working for SVG
fxElements[0].className = classes.join(" ").trim();

// working for HTML and SVG elements
fxElements[0].setAttribute('class', classes.join(" ").trim());
```
We'll make sure to update both this component and the utility functions of the framework. 

Meanwhile, you could locally redefine those utility functions:
```
Util.hasClass = function(el, className) {
  if (el.classList) return el.classList.contains(className);
  else return !!el.getAttribute('class').match(new RegExp('(\\s|^)' + className + '(\\s|$)'));
};

Util.addClass = function(el, className) {
  var classList = className.split(' ');
   if (el.classList) el.classList.add(classList[0]);
   else if (!Util.hasClass(el, classList[0])) el.setAttribute('class', el.getAttribute('class') +  " " + classList[0]);
   if (classList.length > 1) Util.addClass(el, classList.slice(1).join(' '));
};

Util.removeClass = function(el, className) {
  var classList = className.split(' ');
  if (el.classList) el.classList.remove(classList[0]);	
  else if(Util.hasClass(el, classList[0])) {
    var reg = new RegExp('(\\s|^)' + classList[0] + '(\\s|$)');
    el.setAttribute('class', el.getAttribute('class').replace(reg, ' '))
  }
  if (classList.length > 1) Util.removeClass(el, classList.slice(1).join(' '));
};
```

Please let me know if you have any questions. Cheers!

**Comment by claudia-romano** [comment]
Hi there,
we have now updated the framework utility methods and the Reveal Effects component to fix the issue with svg element className. 

Feel free to reopen this issue if you are still experiencing issues.

Cheers!

**Comment by alexandrebuffet** [comment]
Hi, 

Great ! Thanks for your help and code improvment !
