### ISSUE TITLE
Suggestion: data-duration

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-reveal-effects-changelog#4]
Hi Team,

Would be nice to also be able to set the duration of the reveal effect. Is this something you could implement?

Regards,
Yannick

**Comment by claudia-romano** [comment]
Hi Yannick,
you can modify this duration changing the `--reveal-fx-duration` CSS variable defined in the scss file of the component. You can also define a different duration for different type of animations, for example:
```
:root {
  --reveal-fx-duration: 0.6s;
}

// define a different duration for the scale animation
.reveal-fx--scale {
  --reveal-fx-duration: 0.4s;
}
```
Cheers!

**Comment by YannickMol** [comment]
Hi Claudia, thanks for the comment, will try that!
